{
    "name": "Coop - Stock",
    "version": "18.0.1.0.0",
    "category": "Custom",
    "summary": "Custom settings for stock",
    "author": "La Louve, Druidoo",
    "website": "https://github.com/AwesomeFoodCoops/odoo-production",
    "license": "AGPL-3",
    "depends": [
        "stock",
        "stock_account",
        "stock_inventory_valuation_report",
        "stock_scrap_product_report",
        "point_of_sale",
        "purchase_package_qty",
        "purchase_stock",
        "queue_job",
        "sale_stock",
    ],
    "data": [
        "views/action.xml",
        "views/stock_scrap_reason_tag_views.xml",
        "views/menu.xml",
        "views/stock_picking_view.xml",
        "views/stock_inventory_valuation_report.xml",
    ],
    "installable": True,
}
