# -*- coding: utf-8 -*-
{
    'name': 'Roles for Foodcoop',
    'version': '12.0.1.0.0',
    'category': 'Trobz Standard Modules',
    'description': """
    """,
    'author': 'Trobz',
    'website': 'http://www.trobz.com',
    'depends': [
        'base_user_role',
        'pos_payment_terminal',
        'pos_access_right',
        'point_of_sale',
        'coop_default_pricetag',
        'purchase',
        'stock',
        'barcodes_generator_abstract',
        'coop_shift',
        'coop_membership',
        'coop_badge_reader',
        'sales_team',
        'account_export',
        'product_to_scale_bizerba',
        'foodcoop_module',
        'event',
        'project',
        'product_print_category',
        'base_technical_features',
        'mass_mailing_access',
        'pos_report_session_summary',
        'coop_account_check_deposit',
        'coop_account',
        'invisible_menu_groups',
        'coop_print_badge',
        'coop_product_coefficient',
        'coop_inventory_recurrent',
        'maintenance',
        'account_mass_reconcile'
    ],
    'test': [],
    'data': [
        'security/ir.model.access.csv',
        'data/res_groups.xml',
        'data/res_users_role.xml',
        'data/res_users.xml',
        'data/res.users.role.line.csv',
        'data/ir.model.access.csv',
        'views/mass_mailing_views.xml',
        'views/pos_session_views.xml',
        'views/invoicing_views.xml',
        'views/shift_views.xml',
        'views/product_views.xml',
        'views/res_partner_views.xml',
        'views/menu.xml',
    ],

    'installable': True,
    'active': False,
    'application': False
}