{
    "name": "Roles for Foodcoop",
    "version": "18.0.1.0.0",
    "category": "Trobz Standard Modules",
    "author": "Trobz, La Louve",
    "website": "https://github.com/AwesomeFoodCoops/odoo-production",
    "license": "AGPL-3",
    "depends": [
        "base_user_role",
        "pos_payment_terminal",
        "pos_access_right",
        "point_of_sale",
        "coop_default_pricetag",
        "purchase",
        "stock",
        "barcodes_generator_abstract",
        "coop_shift",
        "coop_membership",
        "hr",
        "coop_badge_reader",
        "sales_team",
        "account_export",
        "product_to_scale_bizerba",
        "foodcoop_module",
        "event",
        "project",
        "product_print_category",
        "base_technical_features",
        "mass_mailing_access",
        "pos_report_session_summary",
        "coop_account_check_deposit",
        "coop_account",
        "coop_print_badge",
        "coop_product_coefficient",
        "coop_inventory_recurrent",
        "maintenance",
        "account_mass_reconcile",
        "coop_delivery_category",
        "product_history",
        "base_import_security_group",
        "spreadsheet_dashboard",
        "base_user_role_history",
    ],
    "data": [
        "data/res_groups.xml",
        "data/res_users_role.xml",
        "data/ir.model.access.csv",
        "data/ir_rule.xml",
        "security/ir.model.access.csv",
        "views/mass_mailing_views.xml",
        "views/pos_session_views.xml",
        "views/invoicing_views.xml",
        "views/shift_views.xml",
        "views/product_views.xml",
        "views/res_partner_views.xml",
        "views/menu.xml",
        "report/coop_print_badge_report.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "foodcoop_data_role/static/src/js/web_access_buttons.esm.js",
        ],
    },
    "installable": True,
    "application": False,
}
