# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).

import logging

_logger = logging.getLogger(__name__)


def migrate(cr, version):
    # In v12.0 there was a public default pricelist with the XML ID
    # "product.list0". It no longer exists in v18.0, but databases migrated
    # from older versions may still carry its ir.model.data record.
    # When that record is still present, keep using the referenced pricelist
    # as the default POS pricelist for shops that rely on pricelists.
    cr.execute(
        """
        SELECT res_id
        FROM ir_model_data
        WHERE module = 'product' AND name = 'list0'
        """
    )
    row = cr.fetchone()
    if not row:
        # product.list0 not found -> nothing to do, skip everything.
        _logger.info("product.list0 not found, skipping migration.")
        return

    pricelist_id = row[0]

    # Make sure the referenced pricelist record still exists (the
    # ir.model.data row could be dangling after a partial migration).
    cr.execute("SELECT 1 FROM product_pricelist WHERE id = %s", (pricelist_id,))
    if not cr.fetchone():
        _logger.info(
            "product.list0 points to a missing pricelist (id=%s), skipping migration.",
            pricelist_id,
        )
        return

    # Set product.list0 as the default pricelist on every POS that uses
    # pricelists (use_pricelist = True).
    cr.execute(
        """
        UPDATE pos_config
        SET pricelist_id = %s
        WHERE use_pricelist IS TRUE
        """,
        (pricelist_id,),
    )
    _logger.info(
        "Set product.list0 as default pricelist on %d POS config(s).",
        cr.rowcount,
    )

    # The _check_pricelists constraint requires the default pricelist to be
    # part of available_pricelist_ids when use_pricelist is enabled. Make
    # sure product.list0 is listed as an available pricelist on those POS
    # configs (the m2m relation is auto-generated by the ORM as
    # pos_config_product_pricelist_rel(pos_config_id, product_pricelist_id)).
    cr.execute(
        """
        INSERT INTO pos_config_product_pricelist_rel
            (pos_config_id, product_pricelist_id)
        SELECT c.id, %s
        FROM pos_config c
        WHERE c.use_pricelist IS TRUE
          AND NOT EXISTS (
              SELECT 1
              FROM pos_config_product_pricelist_rel r
              WHERE r.pos_config_id = c.id
                AND r.product_pricelist_id = %s
          )
        """,
        (pricelist_id, pricelist_id),
    )
    _logger.info(
        "Added product.list0 to available pricelists on %d POS config(s).",
        cr.rowcount,
    )

    # Move product.list0 to the top of the pricelist ordering.
    # product.pricelist _order = "sequence, id, name", so the smallest
    # sequence appears first. Use MIN(sequence) - 1 of the other pricelists
    # (falling back to 1 when there is no other pricelist).
    cr.execute(
        """
        UPDATE product_pricelist
        SET sequence = COALESCE(
            (SELECT MIN(sequence) - 1 FROM product_pricelist WHERE id != %s),
            1
        )
        WHERE id = %s
        """,
        (pricelist_id, pricelist_id),
    )
    _logger.info("Moved product.list0 to the first pricelist position.")
